<!DOCTYPE html>



  


<html class="theme-next muse use-motion" lang="zh-Hans">
<head>
  <meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<script src="//cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
<link href="//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css" rel="stylesheet">
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
















  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css" />







<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=5.1.4" rel="stylesheet" type="text/css" />


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=5.1.4">


  <link rel="mask-icon" href="/images/logo.svg?v=5.1.4" color="#222">





  <meta name="keywords" content="Hexo, NexT" />










<meta name="description" content="[TOC] 异常异常体系1. 概述异常对象都是派生于 ==Throwable== 类的一个实例，异常体系如下如所示。RuntimeException 下面是非受查异常。IOException 下面是受查异常。   Throwable 可以用来表示任何可以作为异常抛出的类，分为两种： Error（错误）  和 Exception（异常）。异常和错误的区别是，异常是可以被处理的，而错误是没法处理的。">
<meta property="og:type" content="article">
<meta property="og:title" content="ShiftJava&#x2F;A Java&#x2F;A-10 异常">
<meta property="og:url" content="http:&#x2F;&#x2F;yoursite.com&#x2F;2021&#x2F;08&#x2F;07&#x2F;ShiftJava&#x2F;A%20Java&#x2F;A-10%20%E5%BC%82%E5%B8%B8&#x2F;index.html">
<meta property="og:site_name" content="路漫漫其修远兮">
<meta property="og:description" content="[TOC] 异常异常体系1. 概述异常对象都是派生于 ==Throwable== 类的一个实例，异常体系如下如所示。RuntimeException 下面是非受查异常。IOException 下面是受查异常。   Throwable 可以用来表示任何可以作为异常抛出的类，分为两种： Error（错误）  和 Exception（异常）。异常和错误的区别是，异常是可以被处理的，而错误是没法处理的。">
<meta property="og:locale" content="zh-Hans">
<meta property="og:image" content="http:&#x2F;&#x2F;yoursite.com&#x2F;2021&#x2F;08&#x2F;07&#x2F;ShiftJava&#x2F;A%20Java&#x2F;A-10%20%E5%BC%82%E5%B8%B8&#x2F;assets&#x2F;1563604669873.png">
<meta property="og:updated_time" content="2021-01-06T11:22:32.000Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="http:&#x2F;&#x2F;yoursite.com&#x2F;2021&#x2F;08&#x2F;07&#x2F;ShiftJava&#x2F;A%20Java&#x2F;A-10%20%E5%BC%82%E5%B8%B8&#x2F;assets&#x2F;1563604669873.png">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Muse',
    version: '5.1.4',
    sidebar: {"position":"right","wideth":200,"display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":true},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":1},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="http://yoursite.com/2021/08/07/ShiftJava/A Java/A-10 异常/"/>





  <title>ShiftJava/A Java/A-10 异常 | 路漫漫其修远兮</title>
  








</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  
  
    
  

  <div class="container sidebar-position-right page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/"  class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">路漫漫其修远兮</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle"></p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br />
            
            首页
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal" itemscope itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="http://yoursite.com/2021/08/07/ShiftJava/A%20Java/A-10%20%E5%BC%82%E5%B8%B8/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="Yue">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/images/avatar.gif">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="路漫漫其修远兮">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">ShiftJava/A Java/A-10 异常</h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2021-08-07T19:04:14+08:00">
                2021-08-07
              </time>
            

            

            
          </span>

          

          
            
          

          
          

          
            <span class="post-meta-divider">|</span>
            <span class="page-pv"><i class="fa fa-file-o"></i>
            <span class="busuanzi-value" id="busuanzi_value_page_pv" ></span>
            </span>
          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <p>[TOC]</p>
<h3 id="异常"><a href="#异常" class="headerlink" title="异常"></a>异常</h3><h4 id="异常体系"><a href="#异常体系" class="headerlink" title="异常体系"></a>异常体系</h4><h5 id="1-概述"><a href="#1-概述" class="headerlink" title="1. 概述"></a>1. 概述</h5><p>异常对象<strong>都是派生于 ==Throwable== 类</strong>的一个实例，异常体系如下如所示。RuntimeException 下面是<strong>非受查异常</strong>。IOException 下面是<strong>受查异常</strong>。</p>
<img src="assets/1563604669873.png" alt="1563604669873" style="zoom:77%;" />

<p>Throwable 可以用来表示任何可以作为异常抛出的<strong>类</strong>，分为两种： <strong>Error（错误）</strong>  和 <strong>Exception（异常）</strong>。异常和错误的区别是，<strong>异常是可以被处理的，而错误是没法处理的</strong>。 </p>
<h5 id="2-Error"><a href="#2-Error" class="headerlink" title="2. Error"></a>2. Error</h5><p>其中 Error 用来表示 JVM <strong>无法处理的错误</strong>，对于所有的<strong>编译时期</strong>的错误以及<strong>系统错误</strong>都是通过 Error 抛出的。</p>
<p>例子：<strong>NoClassDefFoundError</strong>：如果 JVM 或者 ClassLoader 实例<strong>尝试加载</strong>（可以通过正常的方法调用，也可能是使用 new 来创建新的对象）<strong>类的时候却找不到类的定义</strong>。要查找的类在<strong>编译的时候是存在</strong>的，<strong>运行的时候却找不到</strong>了。这个错误往往是你使用 new 操作符来创建一个新的对象但却找不到该对象对应的类。这个时候就会导致 NoClassDefFoundError。</p>
<h5 id="3-Exception"><a href="#3-Exception" class="headerlink" title="3. Exception"></a>3. Exception</h5><p><strong>Exception</strong> 是异常，主要分为两种：</p>
<ul>
<li><strong>受查异常</strong> ：程序==<strong>编译阶段</strong>==发生异常，必须要使用 <strong>try…catch</strong>（或者 throws）进行处理否则编译不通过；受查就是<strong>可以检查</strong>到的，与 <strong>IO 操作相关</strong>的很多异常就是这个。比如 ：ClassNotFoundException，NoSuchFieldException，NoSuchMetodException。除了 <strong>RuntimeException</strong> 及其子类以外，都是受查异常。</li>
<li><strong>非受查异常</strong> ：程序==<strong>运行时</strong>==错误，例如除 0 会引发 ArithmeticException，此时程序崩溃并且无法恢复。派生于 <strong>Error</strong> 类和 <strong>RuntimeException 类</strong>的异常。程序运行过程中才能发现的异常，所以是<strong>不能检查</strong>的异常。</li>
</ul>
<p><strong>常见的 RuntimeException 表（非受查异常）</strong>，有时候面试会叫说几个。</p>
<table>
<thead>
<tr>
<th align="center">异常</th>
<th align="center">类型</th>
</tr>
</thead>
<tbody><tr>
<td align="center"><strong>NullPointerException</strong></td>
<td align="center">空指针引用异常</td>
</tr>
<tr>
<td align="center"><strong>ClassCastException</strong></td>
<td align="center">类型强制转换异常</td>
</tr>
<tr>
<td align="center"><strong>IllegalArgumentException</strong></td>
<td align="center">传递非法参数异常</td>
</tr>
<tr>
<td align="center"><strong>ArithmeticException</strong></td>
<td align="center">算术运算异常</td>
</tr>
<tr>
<td align="center">ArrayStoreException</td>
<td align="center">向数组中存放与声明类型不兼容对象异常</td>
</tr>
<tr>
<td align="center"><strong>IndexOutOfBoundsException</strong></td>
<td align="center">下标越界异常</td>
</tr>
<tr>
<td align="center"><strong>NumberFormatException</strong></td>
<td align="center">数字格式异常</td>
</tr>
<tr>
<td align="center">UnsupportedOperationException</td>
<td align="center">不支持的操作异常</td>
</tr>
</tbody></table>
<h4 id="基本使用"><a href="#基本使用" class="headerlink" title="基本使用"></a>基本使用</h4><h5 id="1-Throwable类API"><a href="#1-Throwable类API" class="headerlink" title="1. Throwable类API"></a>1. Throwable类API</h5><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 构造一个新的Throwable对象，这个对象没有详细的描述信息</span></span><br><span class="line">Throwable(); 	</span><br><span class="line"><span class="comment">// 构造一个新的throwable对象，这个对象带有特定的详细描述信息。习惯上所有派生的异常类都支持一个默认的构造器和一个带有详细描述信息的构造器</span></span><br><span class="line">Throwable(String message); </span><br><span class="line"><span class="comment">// 获得Throwable对象的详细描述信息</span></span><br><span class="line"><span class="function">String <span class="title">getMessage</span><span class="params">()</span></span>;</span><br></pre></td></tr></table></figure>

<h5 id="2-异常声明与抛出"><a href="#2-异常声明与抛出" class="headerlink" title="2. 异常声明与抛出"></a>2. 异常声明与抛出</h5><p><strong>受查异常</strong>使用 ==<strong>throws</strong>== 关键词<strong>声明</strong>异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyAnimation</span> </span>&#123;</span><br><span class="line">    <span class="comment">// 可以同时声明多个可能抛出的异常</span></span><br><span class="line">    <span class="function"><span class="keyword">public</span> Image <span class="title">loadlmage</span><span class="params">(String s)</span> <span class="keyword">throws</span> FileNotFoundException, EOFException</span>&#123;</span><br><span class="line">        <span class="comment">//...</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>非受查异常</strong>使用 ==<strong>throw</strong>== 关键词<strong>抛出</strong>异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">EOFException e = <span class="keyword">new</span> EOFException();    <span class="comment">// 构造异常对象</span></span><br><span class="line"><span class="keyword">throw</span> e;    <span class="comment">// 抛出异常对象</span></span><br><span class="line"><span class="keyword">throw</span> <span class="keyword">new</span> EOFException(<span class="string">"File is not found"</span>);    <span class="comment">// 抛出异常对象且带异常有信息</span></span><br></pre></td></tr></table></figure>

<h5 id="3-异常链"><a href="#3-异常链" class="headerlink" title="3. 异常链"></a>3. 异常链</h5><p><strong>再次抛出异常与异常链</strong></p>
<p><strong>异常链</strong>是指在进行一个<strong>异常处理时抛出了另外一个异常</strong>，从而产生了一个<strong>异常链条</strong>，大多用于将<strong>受查异常封装</strong>成为非受查异常或者 RuntimeException。如果封装原有一个异常而抛出另一个<strong>新的</strong>异常时一定要<strong>包含原有</strong>的异常，将原始异常设置为新异常的<strong>原因</strong>，这样处理程序才可以通过 <strong>getCause</strong>() 和 initCause() 方法来访问异常最终的<strong>根源</strong>。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">// access the database</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (SQLException e) &#123;</span><br><span class="line">    <span class="comment">// 构造新的异常对象</span></span><br><span class="line">    Throwable se = <span class="keyword">new</span> ServletException (<span class="string">"database error"</span>); </span><br><span class="line">    <span class="comment">// 把原本异常e传入新异常对象</span></span><br><span class="line">    se.initCause(e);    </span><br><span class="line">    <span class="keyword">throw</span> se;   <span class="comment">// 抛出新对象</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>当捕获到异常时， 就可以使用下面这条语句<strong>重新</strong>得到原始异常：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Throwable e = se.getCause();</span><br></pre></td></tr></table></figure>

<p><strong>强烈建议</strong>使用这种包装技术。</p>
<h5 id="4-自定义异常类"><a href="#4-自定义异常类" class="headerlink" title="4. 自定义异常类"></a>4. 自定义异常类</h5><p>自定义异常类只需<strong>继承 Exception</strong> 类或者其子类即可。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">FileFormatException</span> <span class="keyword">extends</span> <span class="title">IOException</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="title">FileFormatException</span><span class="params">()</span> </span>&#123;</span><br><span class="line">        <span class="keyword">this</span>(<span class="string">"The file format is not good."</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="title">FileFormatException</span><span class="params">(String gripe)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">super</span>(gripe);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h5 id="5-覆写父类异常方法"><a href="#5-覆写父类异常方法" class="headerlink" title="5. 覆写父类异常方法"></a>5. 覆写父类异常方法</h5><p>如果在子类中<strong>覆写</strong>了超类的一个方法， <strong>子类</strong>方法中声明的受查异常<strong>不能比超类方法中声明的异常更通用</strong> （子类方法中可以抛出<strong>更特定</strong>的异常， 或者根本不抛出任何异常）。</p>
<p>如果超类方法没有抛出任何受查异常，子类也不能抛出任何受查异常。</p>
<p>总之就是，<strong>超类异常范围最广泛</strong>，子类抛出的异常<strong>只能更加详细</strong>。<strong>覆写的方法不能拓展父类异常的范围</strong>。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">SuperClass</span></span>&#123;</span><br><span class="line">    <span class="keyword">public</span> <span class="keyword">void</span> someMethod <span class="keyword">throws</span> Exception1 &#123;</span><br><span class="line">        <span class="comment">//....</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">SubClass</span> <span class="keyword">extends</span> <span class="title">SuperClass</span> </span>&#123;</span><br><span class="line">    <span class="comment">// Error子类方法比父类异常范围更大</span></span><br><span class="line">    <span class="meta">@Override</span></span><br><span class="line">    <span class="keyword">public</span> <span class="keyword">void</span> someMethod <span class="keyword">throws</span> Exception1, Exception2 &#123;	</span><br><span class="line">        <span class="comment">//....</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">SubClass</span> <span class="keyword">extends</span> <span class="title">SuperClass</span> </span>&#123;</span><br><span class="line">    <span class="comment">// 如果Exception3继承Exception1是可以的</span></span><br><span class="line">    <span class="meta">@Override</span></span><br><span class="line">    <span class="keyword">public</span> <span class="keyword">void</span> someMethod <span class="keyword">throws</span> Exception3 &#123;	</span><br><span class="line">        <span class="comment">//....</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h4 id="try-catch-finally"><a href="#try-catch-finally" class="headerlink" title="try-catch-finally"></a>try-catch-finally</h4><h5 id="1-概述-1"><a href="#1-概述-1" class="headerlink" title="1. 概述"></a>1. 概述</h5><p>finally 用于<strong>回收资源</strong>。涉及<strong>资源操作</strong>的都需要执行！！比如文件打开、Redis 或 MySQL 连接等。不管是<strong>否有异常被捕获</strong>， finally 子句中的代码<strong>都被执行</strong>。</p>
<p>try 语句可以只有 finally 子句，而没有 catch 子句。</p>
<p>finally 语句中<strong>可能也会产生异常</strong>！如资源关闭 close() 方法的异常。此时原始的异常将会丢失，转而抛出 close 方法的异常。</p>
<p><strong>注意</strong>：就算 <strong>try 语句中含有 return 语句，那么 finally 语句依然会执行</strong>。try 代码块中的 <strong>break 或 continue</strong> 语句也可能使控制权进入 finally 代码块。</p>
<h5 id="2-带return的finally语句"><a href="#2-带return的finally语句" class="headerlink" title="2. 带return的finally语句"></a>2. 带return的finally语句</h5><p>当 <strong>finally 子句包含 return 语句</strong>时，将会出现一种<strong>意想不到</strong>的结果，假设利用 return 语句从 <strong>try</strong> 语句块中<strong>退出</strong>。<strong>在方法返回前，finally 子句的内容将被执行</strong>。如果 finally 子句中也有一个 return 语句，这个返回值将会==<strong>覆盖</strong>==原始的<strong>返回值</strong>。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">int</span> <span class="title">f</span><span class="params">(<span class="keyword">int</span> n)</span></span>&#123;</span><br><span class="line">    <span class="keyword">try</span>&#123;</span><br><span class="line">        <span class="keyword">int</span> r = n * n;</span><br><span class="line">        <span class="comment">// 如果try子句含有return</span></span><br><span class="line">        <span class="keyword">return</span> r;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">        <span class="comment">// catch里面也有return</span></span><br><span class="line">        <span class="keyword">return</span> <span class="number">4</span>;</span><br><span class="line">    &#125; <span class="keyword">finally</span>&#123;</span><br><span class="line">        <span class="keyword">if</span> (n == <span class="number">2</span>) &#123;</span><br><span class="line">            <span class="comment">// finally中的return覆盖try中的return</span></span><br><span class="line">            <span class="keyword">return</span> <span class="number">0</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>如果调用 f(2), 那么 try 语句块的计算结果为 r = 4, 并执行 return 语句. 然而在方法真正<strong>返回前</strong>，还要执行 finally 子句。finally 子句将使得<strong>方法返回 0</strong>, 这个返回值<strong>覆盖</strong>了原始的返回值 4。如果 <strong>catch 语句块里面有 return 语句</strong>，那么 finally <strong>依然会覆盖</strong>这个结果。</p>
<p><strong>不要在 finally 语句中使用 return，这不是 finally 语句的用处。</strong></p>
<h5 id="3-带资源的try语句"><a href="#3-带资源的try语句" class="headerlink" title="3. 带资源的try语句"></a>3. 带资源的try语句</h5><p>如果需要<strong>关闭资源</strong>，最好使用带资源的 try 语句。前提是这个资源实现了 <strong>AutoCloseable</strong> 接口， Java SE7 为这种代码模式提供了一个很有用的快捷方式。AutoCloseable 接口有一个方法：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">close</span><span class="params">()</span> <span class="keyword">throws</span> Exception</span></span><br></pre></td></tr></table></figure>

<p>有的资源<strong>没有实现这个接口</strong>就<strong>不能</strong>使用带资源的 try 语句。</p>
<p>带资源的 try 语句（try-with-resources) 的最简形式如下：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (Resource res = ...)&#123;</span><br><span class="line">    <span class="comment">// work with res</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>try 块正常或者发生异常退出时，会<strong>自动调用 res.close()</strong>。就<strong>像使用了 finally 子句</strong>。</p>
<p>还可以指定<strong>多个资源</strong>。例如：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (Scanner in = <span class="keyword">new</span> Scanner (<span class="keyword">new</span> FileInputStream(<span class="string">'7usr/share/dict/words"),  "UTF-8");</span></span><br><span class="line"><span class="string">PrintWriter out = new Pri ntWriter("out.txt"))&#123;</span></span><br><span class="line"><span class="string">    while (in.hasNex())</span></span><br><span class="line"><span class="string">    System.out.println(in.next().toUpperCase());</span></span><br><span class="line"><span class="string">&#125;</span></span><br></pre></td></tr></table></figure>

<p>不论这个块如何退出，in 和 out 都会<strong>关闭</strong>。</p>
<h5 id="4-问题总结"><a href="#4-问题总结" class="headerlink" title="4. 问题总结"></a>4. 问题总结</h5><blockquote>
<p><strong>如果执行finally代码块之前方法返回了结果或者JVM退出了，这时finally块中的代码还会执行吗？</strong></p>
</blockquote>
<p>只有在 try 里面通过 <strong>System.exit(0)</strong> 来<strong>退出 JVM</strong> 的情况下 finally 块中的代码才<strong>不会</strong>执行，其他 return 等情况<strong>都会调用</strong>，所以在<strong>不终止 JVM 的情况下 finally 中的代码一定会执行</strong>。</p>
<blockquote>
<p><strong>finally语句块一定会执行吗？</strong></p>
</blockquote>
<p>不一定，分情况。因为首先想要执行 finally 块的<strong>前提是必须执行到了 try 块</strong>，当在 try 块或者 catch 块中<strong>有 System.exit(0);</strong> 这样的语句存在时 finally 块就<strong>不会被执行</strong>到了，因为程序<strong>被结束</strong>了。此外当在 try 块或者 catch 块里 return 时 finally 会被执行；而且 finally 块里 return 语句会把 try 块或者 catch 块里的 return 语句效果给覆盖掉<strong>且吞掉了异常</strong>。当一个线程在执行 try 语句块或者 catch 语句块时被打断（interrupted）或者被终止（killed），与其相对应的 finally 语句块可能不会执行。还有更极端的情况，就是在线程运行 try 语句块或者 catch 语句块时，突然<strong>断电</strong>。</p>
<h4 id="使用异常技巧"><a href="#使用异常技巧" class="headerlink" title="使用异常技巧"></a>使用异常技巧</h4><p>来自 Java Core。</p>
<ul>
<li>多使用代码检查机制。<strong>捕获异常的开销非常大</strong>。</li>
<li>不要过分细化异常。</li>
<li>利用异常层次结构，不要只抛出 RuntimeException 异常。应该寻找更加适当的子类或创建自己的异常类。不要只捕获 Thowable 异常， 否则，会使程序代码更难读、更难维护。将一种异常转换成另一种更加适合的异常时不要犹豫。</li>
<li>不要压制异常。不要羞于传递异常。</li>
<li>在检测错误时，”苛刻” 要比放任更好。</li>
<li>早抛出，晚捕获。</li>
<li>多个 catch 块的次序应该是具体异常放在其祖先类的前面，否则后面的 catch 语句可能进入不了。</li>
</ul>
<h4 id="参考资料"><a href="#参考资料" class="headerlink" title="参考资料"></a>参考资料</h4><ul>
<li><a href="https://www.tianmaying.com/tutorial/Java-Exception" target="_blank" rel="noopener">Java 入门之异常处理</a></li>
</ul>

      
    </div>
    
    
    

    

    

    

    <footer class="post-footer">
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2021/08/07/ShiftJava/A%20Java/A%20Java%E5%9F%BA%E7%A1%80/" rel="next" title="ShiftJava/A Java/A Java基础">
                <i class="fa fa-chevron-left"></i> ShiftJava/A Java/A Java基础
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2021/08/07/ShiftJava/A%20Java/A-1%20%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E4%B8%8E%E7%A8%8B%E5%BA%8F%E7%BB%93%E6%9E%84/" rel="prev" title="ShiftJava/A Java/A-1 数据类型与程序结构">
                ShiftJava/A Java/A-1 数据类型与程序结构 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>



    <div class="post-spread">
      
    </div>
  </div>


          </div>
          


          

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
      <div id="sidebar-dimmer"></div>
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name">Yue</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives">
              
                  <span class="site-state-item-count">163</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            

            

          </nav>

          

          

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-3"><a class="nav-link" href="#异常"><span class="nav-number">1.</span> <span class="nav-text">异常</span></a><ol class="nav-child"><li class="nav-item nav-level-4"><a class="nav-link" href="#异常体系"><span class="nav-number">1.1.</span> <span class="nav-text">异常体系</span></a><ol class="nav-child"><li class="nav-item nav-level-5"><a class="nav-link" href="#1-概述"><span class="nav-number">1.1.1.</span> <span class="nav-text">1. 概述</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#2-Error"><span class="nav-number">1.1.2.</span> <span class="nav-text">2. Error</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#3-Exception"><span class="nav-number">1.1.3.</span> <span class="nav-text">3. Exception</span></a></li></ol></li><li class="nav-item nav-level-4"><a class="nav-link" href="#基本使用"><span class="nav-number">1.2.</span> <span class="nav-text">基本使用</span></a><ol class="nav-child"><li class="nav-item nav-level-5"><a class="nav-link" href="#1-Throwable类API"><span class="nav-number">1.2.1.</span> <span class="nav-text">1. Throwable类API</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#2-异常声明与抛出"><span class="nav-number">1.2.2.</span> <span class="nav-text">2. 异常声明与抛出</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#3-异常链"><span class="nav-number">1.2.3.</span> <span class="nav-text">3. 异常链</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#4-自定义异常类"><span class="nav-number">1.2.4.</span> <span class="nav-text">4. 自定义异常类</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#5-覆写父类异常方法"><span class="nav-number">1.2.5.</span> <span class="nav-text">5. 覆写父类异常方法</span></a></li></ol></li><li class="nav-item nav-level-4"><a class="nav-link" href="#try-catch-finally"><span class="nav-number">1.3.</span> <span class="nav-text">try-catch-finally</span></a><ol class="nav-child"><li class="nav-item nav-level-5"><a class="nav-link" href="#1-概述-1"><span class="nav-number">1.3.1.</span> <span class="nav-text">1. 概述</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#2-带return的finally语句"><span class="nav-number">1.3.2.</span> <span class="nav-text">2. 带return的finally语句</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#3-带资源的try语句"><span class="nav-number">1.3.3.</span> <span class="nav-text">3. 带资源的try语句</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#4-问题总结"><span class="nav-number">1.3.4.</span> <span class="nav-text">4. 问题总结</span></a></li></ol></li><li class="nav-item nav-level-4"><a class="nav-link" href="#使用异常技巧"><span class="nav-number">1.4.</span> <span class="nav-text">使用异常技巧</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#参考资料"><span class="nav-number">1.5.</span> <span class="nav-text">参考资料</span></a></li></ol></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2021</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Yue</span>

  
</div>









        
<div class="busuanzi-count">
  <script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>

  

  
</div>








        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  
    <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>
  

  
  
    <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.4"></script>



  
  

  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.4"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.4"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.4"></script>



  


  




	





  





  












  





  

  

  

  
  

  

  

  

</body>
</html>
